// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdgvVIvXHrrmVu2fmjB9Nzp45rx1b77XU',
    appId: '1:521941804665:web:f132a90304b422a1ad96a8',
    messagingSenderId: '521941804665',
    projectId: 'animaledu-acc',
    authDomain: 'animaledu-acc.firebaseapp.com',
    storageBucket: 'animaledu-acc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCccklmGnU49p_Yq4twOWFJzGD8UWWyfNk',
    appId: '1:521941804665:android:05b61061584061d1ad96a8',
    messagingSenderId: '521941804665',
    projectId: 'animaledu-acc',
    storageBucket: 'animaledu-acc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiZwKu066IdCJrq3q5nIzN0fnIGJcrbZI',
    appId: '1:521941804665:ios:4a031cf739f39500ad96a8',
    messagingSenderId: '521941804665',
    projectId: 'animaledu-acc',
    storageBucket: 'animaledu-acc.firebasestorage.app',
    iosBundleId: 'com.example.paMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiZwKu066IdCJrq3q5nIzN0fnIGJcrbZI',
    appId: '1:521941804665:ios:4a031cf739f39500ad96a8',
    messagingSenderId: '521941804665',
    projectId: 'animaledu-acc',
    storageBucket: 'animaledu-acc.firebasestorage.app',
    iosBundleId: 'com.example.paMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdgvVIvXHrrmVu2fmjB9Nzp45rx1b77XU',
    appId: '1:521941804665:web:c3b4d0de119ade56ad96a8',
    messagingSenderId: '521941804665',
    projectId: 'animaledu-acc',
    authDomain: 'animaledu-acc.firebaseapp.com',
    storageBucket: 'animaledu-acc.firebasestorage.app',
  );
}
